export const GET_DESIGNERS_SUCCESS      = "GET_DESIGNERS_SUCCESS";
export const GET_DESIGNERS_FAILURE      = "GET_DESIGNERS_FAILURE";
export const GET_DESIGNERS_STARTED      = "GET_DESIGNERS_STARTED";
export const GET_DESIGNERS_ENDED        = "GET_DESIGNERS_ENDED";
export const DESIGNERS_PAGE_UNLOADED    = "DESIGNERS_PAGE_UNLOADED";
export const SET_DESIGNERS_FILTER       = "SET_DESIGNERS_FILTER";
export const UPDATE_CHECKED_ITEMS       = "UPDATE_CHECKED_ITEMS";
export const TEMPORARY_TOGGLE_STATUS    = "TEMPORARY_TOGGLE_STATUS";

export const NOTIFICATION_SUCCESS       = "NOTIFICATION_SUCCESS";
export const NOTIFICATION_FAILURE       = "NOTIFICATION_FAILURE";
export const NOTIFICATION_HIDDEN        = "NOTIFICATION_HIDDEN";

export const BATCH_UPDATE_DESIGNERS_SUCCESS       = "BATCH_UPDATE_DESIGNERS_SUCCESS";

export const GET_DESIGNER_STARTED       = 'GET_DESIGNER_STARTED';
export const GET_DESIGNER_FAILURE       = 'GET_DESIGNER_FAILURE';
export const GET_DESIGNER_SUCCESS       = 'GET_DESIGNER_SUCCESS';
export const DESIGNER_PAGE_UNLOADED     = "DESIGNER_PAGE_UNLOADED";
export const CHANGE_DESIGNER_INFO       = "CHANGE_DESIGNER_INFO";
export const UPDATE_DESIGNER_STARTED    = "UPDATE_DESIGNER_STARTED";
export const UPDATE_DESIGNER_FAILURE    = "UPDATE_DESIGNER_FAILURE";
export const UPDATE_DESIGNER_SUCCESS    = "UPDATE_DESIGNER_SUCCESS";

export const GET_DESIGNER_STATS_STARTED       = 'GET_DESIGNER_STATS_STARTED';
export const GET_DESIGNER_STATS_FAILURE       = 'GET_DESIGNER_STATS_FAILURE';
export const GET_DESIGNER_STATS_SUCCESS       = 'GET_DESIGNER_STATS_SUCCESS';

export const OPEN_MODAL                 = 'OPEN_MODAL';
export const CLOSE_MODAL                = 'CLOSE_MODAL';
export const MODAL_CLOSING              = 'MODAL_CLOSING';
export const SET_MODAL_CONTENT          = 'SET_MODAL_CONTENT';

export const GET_WITHDRAW_SUCCESS       = "GET_WITHDRAW_SUCCESS";
export const GET_WITHDRAW_FAILURE       = "GET_WITHDRAW_FAILURE";
export const GET_WITHDRAW_STARTED       = "GET_WITHDRAW_STARTED";
export const DELETE_WITHDRAW            = "DELETE_WITHDRAW";
export const WITHDRAW_PAGE_UNLOADED     = "WITHDRAW_PAGE_UNLOADED";
export const SET_WITHDRAW_FILTER        = "SET_WITHDRAW_FILTER";
export const GET_WITHDRAW_ENDED         = "GET_WITHDRAW_ENDED";
export const UPDATE_WITHDRAW_CHECKED_ITEMS       = "UPDATE_WITHDRAW_CHECKED_ITEMS";
export const TEMPORARY_TOGGLE_WITHDRAW_STATUS    = "TEMPORARY_TOGGLE_WITHDRAW_STATUS";

export const GET_DESIGNS_SUCCESS        = "GET_DESIGNS_SUCCESS";
export const GET_DESIGNS_FAILURE        = "GET_DESIGNS_FAILURE";
export const GET_DESIGNS_STARTED        = "GET_DESIGNS_STARTED";
export const DELETE_DESIGNS             = "DELETE_DESIGNS";
export const DESIGNS_PAGE_UNLOADED      = "DESIGNS_PAGE_UNLOADED";
export const SET_DESIGNS_FILTER         = "SET_DESIGNS_FILTER";
export const GET_DESIGNS_ENDED          = "GET_DESIGNS_ENDED";
export const UPDATE_DESIGNS_CHECKED_ITEMS       = "UPDATE_DESIGNS_CHECKED_ITEMS";
export const TEMPORARY_TOGGLE_DESIGNS_STATUS    = "TEMPORARY_TOGGLE_DESIGNS_STATUS";

export const DASHBOARD_PAGE_UNLOADED    = "DASHBOARD_PAGE_UNLOADED";
export const GET_SUMMARY_SUCCESS        = "GET_SUMMARY_SUCCESS";
export const GET_SUMMARY_FAILURE        = "GET_SUMMARY_FAILURE";
export const GET_SUMMARY_STARTED        = "GET_SUMMARY_STARTED";
export const GET_REPORT_SUCCESS         = "GET_REPORT_SUCCESS";
export const GET_REPORT_FAILURE         = "GET_REPORT_FAILURE";
export const GET_REPORT_STARTED         = "GET_REPORT_STARTED";